controller_list:
  - name: arm/position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: joint_trajectory_controller
    type: effort_controllers/JointTrajectoryController
    joints:
      - wheel_left_joint
      - wheel_right_joint


  
      

