controller_list:
  - name: fake_aa_controller
    joints:
      - world_vj
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_mp500_controller
    joints:
      - world_vj
      - wheel_left_joint
      - wheel_right_joint
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_gripper_controller
    joints:
      []