mp500:

## joint_names
  joint_names: [wheel_left_joint, wheel_right_joint]
  # Publish all joint states -----------------------------------

## joint trajectory controller
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
       - wheel_left_joint
       - wheel_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        wheel_left_joint: {trajectory: 0.1, goal: 0.1}
        wheel_right_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    required_drive_mode: 7

## control_mode_adapter
  max_command_silence: 0.5


